on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        env:
          PROJET_NAME: projectgroupe5
          CONTAINER_ENV: groupe5-container-env
          CONTAINER_APP: groupe5-container-app
          LOCATION: francecentral
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - uses: actions/checkout@v3
        - uses: hadolint/hadolint-action@v3.1.0
          with:
            dockerfile: Dockerfile
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.PROJET_NAME }}:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.PROJET_NAME }}:${{ github.sha }}

        - name: Create Azure container environment
          run: |
            az containerapp env create -n ${{ env.CONTAINER_ENV }} -g  ${{ secrets.RESOURCE_GROUP }} --location ${{ env.LOCATION }}

        - name: Build and deploy Container App 
          uses: azure/container-apps-deploy-action@v1
          with:
            containerAppName: ${{ env.CONTAINER_APP }}
            containerAppEnvironment: ${{ env.CONTAINER_ENV }}
            imageToDeploy: ${{ secrets.REGISTRY_LOGIN_SERVER }}/projectgroupe5:${{ github.sha }}
            acrName: ${{ secrets.REGISTRY_USERNAME }}
            acrUsername: ${{ secrets.REGISTRY_USERNAME }}
            acrPassword: ${{ secrets.REGISTRY_PASSWORD }}
            resourceGroup: ${{ secrets.RESOURCE_GROUP }}